[[plugins]]
package = "netlify-plugin-flutter"
[plugins.inputs]
channel = "stable"

[build]
command = "flutter build web --release"
publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
