[[plugins]]
package = "netlify-plugin-flutter"
[plugins.inputs]
channel = "stable"

[build]
command = "flutter build web --release"
publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/flutter_service_worker.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/AssetManifest.json"
[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/FontManifest.json"
[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/manifest.json"
[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/main.dart.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
