name: baseqat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  supabase_flutter: ^2.10.0
  flutter_bloc: ^9.1.1
  gradient_borders: ^1.0.2
  carousel_slider_plus: ^7.0.1
  smooth_page_indicator: ^1.2.0+3
  web: any
  universal_html: ^2.2.4
  connectivity_plus: ^7.0.0
  logger : ^2.6.1
  retry: ^3.1.2
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2
  flutter_osm_plugin: ^1.4.2
  url_launcher: ^6.3.2
  flutter_card_swiper: ^7.0.2
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  iconsax: ^0.0.8
  flutter_gemini: ^3.0.0
  record: ^6.1.1
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1
  flutter_tts: ^4.2.3
  record_web: any
  audioplayers: ^6.5.1
  translator: ^1.0.4+1
  pointer_interceptor: ^0.10.1+2
  device_preview: ^1.3.1

  lottie: ^3.3.2
  flutter_map: ^8.2.2
  font_awesome_flutter: ^10.10.0
  image_picker: ^1.2.0
  easy_localization: ^3.0.8
  carousel_slider: ^5.1.1
  flutter_inappwebview: ^6.0.0
  flag: ^7.0.2
#  QR
  permission_handler: ^12.0.1
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0      # For generating QR codes
  share_plus: ^10.0.0
  uni_links: ^0.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^4.5.1
  flutter_cache_manager: ^3.4.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  shimmer: ^3.0.0
#  image_picker_for_web: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true # 
  assets: 
    - assets/
    - assets/images/
    - assets/translations/
    - assets/animations/

  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterMedium.ttf
          weight: 500

